include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - .fvm/
    - .devcontainer/
    - .git/
    - .dart_tool/
    - build/
  errors:
    annotate_overrides: ignore
    overridden_fields: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_relative_imports
    - prefer_single_quotes