// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs_t09W78bir4VUaEBuVWuRQzA06eN-VI',
    appId: '1:74581911787:web:a62ea3de66ba2f7cd976ae',
    messagingSenderId: '74581911787',
    projectId: 'twittergb-aca55',
    authDomain: 'twittergb-aca55.firebaseapp.com',
    storageBucket: 'twittergb-aca55.appspot.com',
    measurementId: 'G-Q360TDG916',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2__2GQ7k9VFijajlkTVPMqDNEMRgJJPk',
    appId: '1:74581911787:android:54658deaef5f6455d976ae',
    messagingSenderId: '74581911787',
    projectId: 'twittergb-aca55',
    storageBucket: 'twittergb-aca55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClzjTmKB125ybQJAfmmJ0D3BZpKJPSKfA',
    appId: '1:74581911787:ios:0947bf02258035c1d976ae',
    messagingSenderId: '74581911787',
    projectId: 'twittergb-aca55',
    storageBucket: 'twittergb-aca55.appspot.com',
    iosClientId:
        '74581911787-e55a8ipkn8eireetjdl2hmuv8ariar33.apps.googleusercontent.com',
    iosBundleId: 'com.wendellrocha.twittergb',
  );
}
