name: dependencies
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  asuka: ^2.0.0+1
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  flutter_triple: ^1.2.7+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
