name: dependencies
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  asuka: ^2.0.0+1
  dartz: ^0.10.1
  dio: ^4.0.6
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  timeago: ^3.2.2
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  flutter_triple: ^1.2.7+2
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  firebase_storage: ^10.3.1
  modular_triple_bind: ^1.0.0
  cloud_firestore: ^3.2.1
  image_picker: ^0.8.5+3
  extended_masked_text: ^2.3.1
  rxdart: ^0.27.4
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

