name: common
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  dependencies:
    path: '../dependencies'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
